#init ricette db
docker exec -i instagnam_ricettedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_completa (id,autore,preparazione,titolo) values(1,'Cristiano','Metti il prosciutto nel panino','Panino al prosciutto');"
docker exec -i instagnam_ricettedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_completa (id,autore,preparazione,titolo) values(2,'Cristiano','Metti la mortadella nella pizza','Pizza e mortazza');"
docker exec -i instagnam_ricettedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_completa (id,autore,preparazione,titolo) values(3,'Gennaro','Unisci i fagioli con il tonno','Tonno e fagioli');"
docker exec -i instagnam_ricettedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_completa (id,autore,preparazione,titolo) values(4,'Antonino','... e alla fine inforna','Pizza margherita');"
docker exec -i instagnam_ricettedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_completa (id,autore,preparazione,titolo) values(5,'Benedetta','Unisci il tonno con i fagioli','Tonno e fagioli');"
docker exec -i instagnam_ricettedb_1 mysql --user=user --password=password db  <<< "update hibernate_sequence set next_val=6"
#init connessioni db
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(1,'Gennaro','Cristiano');"
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(2,'Cristiano','Gennaro');"
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(3,'Cristiano','Paolo');"
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(4,'Gennaro','Paolo');"
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(5,'Antonino','Anna');"
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(6,'Benedetta','Anna');"
docker exec -i instagnam_connessionidb_1 mysql --user=user --password=password db  <<< "update hibernate_sequence set next_val=7"
#init ricetteseguite db
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta (id,autore,titolo) values(1,'Cristiano','Panino al prosciutto');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta (id,autore,titolo) values(2,'Cristiano','Pizza e mortazza');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta (id,autore,titolo) values(3,'Gennaro','Tonno e fagioli');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta (id,autore,titolo) values(4,'Antonino','Pizza margherita');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta (id,autore,titolo) values(5,'Benedetta','Tonno e fagioli');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "update hibernate_sequence set next_val=6"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(1,'Gennaro','Cristiano');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(2,'Cristiano','Gennaro');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(3,'Cristiano','Paolo');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(4,'Gennaro','Paolo');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(5,'Antonino','Anna');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into connessione (id,followed,follower) values(6,'Benedetta','Anna');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "update hibernate_sequence set next_val=7"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(1,'Cristiano',1,'Panino al prosciutto','Gennaro');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(2,'Cristiano',1,'Panino al prosciutto','Paolo');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(3,'Cristiano',2,'Pizza e mortazza','Gennaro');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(4,'Cristiano',2,'Pizza e mortazza','Paolo');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(5,'Gennaro',3,'Tonno e fagioli','Cristiano');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(6,'Gennaro',3,'Tonno e fagioli','Paolo');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(7,'Antonino',4,'Pizza margherita','Anna');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "insert into ricetta_seguita (id,autore_ricetta,id_ricetta,titolo_ricetta,utente_follower) values(8,'Benedetta',5,'Tonno e fagioli','Anna');"
docker exec -i instagnam_ricetteseguitedb_1 mysql --user=user --password=password db  <<< "update hibernate_sequence set next_val=9"